### ISSUE TITLE
Data corruption when opening HID during CDC data transfer

### ISSUE THREAD

**Issue by danielsulik** [majbthrd/CDCHIDwidget#1]
Hi

First of all thank you for sharing your code. I have used your code as a starting point for my project using HID and CDC interface. I managed to build it for STM32F072 and STM32L152 and all seemed OK until I started to do thorough testing. I am experiencing data corruption if I try to run both interfaces at the same time, however it is not happening always. I am testing on windows and linux (ubuntu 16, 18 and raspbian jessie) and experiencing the same issue on all OSes. To access HID i/f I use hidapi library.
Here are few scenarios in my testing.
1. Host opens HID interface, sends 64 byte data to the device, reads back and compares. If received data is the same as sent continue the test otherwise exit with error code. While HID test is running hosts open CDC i/f and do the same. Sends test data of variable length (1 byte to 1234 bytes)  to device and device loops the same data back to the host. Host reads the data and compares. In this scenario all seems OK.
Data corruption occurs in the following scenario:
1. Hosts open CDC first and run the same test as above. Then host opens HID and the host receives corrupted data. The corrupted data contains contains descriptor strings. Seems like EP0 data gets into data EP for CDC. this happens whenever I  re-enumerate USB deviceI or try to read manufacturer, serial no, etc.
My feeling is there might a problem with USB IRQ handler not dealing with multiple requests at the same time. Perhaps you have an better idea. Your help is appreciated.

HAL lib I am using is 1.6.0, 1.8.0. 1.9.0 and all demonstrate the same problem.
 
Best regards
Daniel

**Comment by majbthrd** [comment]
In your testing scenarios, are you using your STM32L152 adaptation of the code (rather than the STM32F072 in the original github code)?

I spent some time trying to reproduce the behavior that you describe, but to no avail.

The testing that I did was with a STM32F072 Discovery eval board.

My only change to the github STM32 code was to add to vendorhid.c:66 (comment "insert code here"):

`memcpy(TxDataBuffer, RxDataBuffer, HID_EP_SIZE);`

so as to mimic the HID echo behavior that you describe.

I also put a jumper PA9 and PA10 on the eval board to create a hardware loopback for the first UART.

I'll include the HIDAPI code below, but it repeatedly sends a message which changes every iteration.  If the response doesn't match what is sent, a fatal error is generated.

I then follow your procedure of opening the CDC first and then the HID second.  The serial data echoes back as does the HID.  I don't see any corruption (regardless of which order interfaces are opened).

[hidecho.c.txt](https://github.com/majbthrd/CDCHIDwidget/files/3287074/hidecho.c.txt)
[Makefile.txt](https://github.com/majbthrd/CDCHIDwidget/files/3287077/Makefile.txt)

**Comment by danielsulik** [comment]
Hi,

 

Thank you for your prompt reply, I rally appreciate it. I will build it for SM32F072 and send the fw and test code to you with all instructions.

Please give me some time, will back to you soon.

 

Regards

Daniel

**Comment by danielsulik** [comment]
Hi again,

 

Please find the hex for F072 discovery board in the attachment.

My test code is in cdchidtes.zip, it uses tcl scripting language. 

 

LINUX

--------

If you test on linux simply install hidapi and then my wrapper for tcl from here

https://github.com/danielsulik/hidapi-tcl

tcl is usually installed by default on all linux distros.

You can also test on vmware player

 

WINDOWS

--------------

to install on windows use the inf file in the attachment.

You can use the same tcl script ,

Simply install activetcl https://www.activestate.com/products/activetcl/

 

On win8 and win10 you might need to bypass signature checking.

 

 

TEST CDC run

-------------------

sudo tclsh cdctest.tcl -c /dev/ttyACM0 -n 10000 -l 1234 -rl
for more info type sudo tclsh cdctest.tcl -h

the command above simple sends random variable length from 1 to 1234 bytes long in 10000 packets

 

TEST HID run
------------------

While the above test is running type command below. Occasionally the CDC gets corrupted data as shown in the picture below.
sudo tclsh hidtest.tcl -n 0

 

For more info type sudo tclsh hidtest.tcl -h

the command above simple opens HID i/f and enumerates bus and reads some descriptors.

To send more data set -n to > 0

 

Perhaps, I am doing something wrong in my code, however I often see device descriptors shown in the CDC data.

Source also in the attachment. It is using most of your code, I just adapted it a bit to my needs and simplify the API

for the end user.  

 

If you prefer we can talk directly via email.

 

Thank you for your help

Daniel

 

Snapshot from my test on vmware below:

You can also notice manufacturer descriptor read got screwed up on enumeration in HID part.

**Comment by danielsulik** [comment]
Hi,
I noticed I did not reply to all your question, sorry for that.

> In your testing scenarios, are you using your STM32L152 adaptation of the code (rather than the STM32F072 in the original github code)?
I have t running on L152, L162 and F072.

There is no real UART involved in the design, so no need for loopback jumper. There is simply a raw CDC i/f and HID i/f
with loopback in user code.

Regards 
Daniel

**Comment by majbthrd** [comment]
I have spent further time on this and just haven't seen any evidence of the problems that you claim, and your test setup involves code that you "just adapted it a bit to my needs and simplify the API for the end user".

I've been using a close variant of this code for several years now, and it defies credibility that I wouldn't have seen such a failure mode.

When you adopt and modify code, you are responsible for debugging that modified code.  You've done such modifications not only to the firmware but to the PC HIDAPI code as well (by creating an unnecessary, additional protocol translation layer between TCL and HIDAPI).

It is not reasonable to make all such changes and then hand those back to one of the original author to try to get them to debug it on your behalf.  You are on your own.

**Comment by danielsulik** [comment]
Hi,

 

Thank you for your reply. Just one more question. Have you seen any problem with my hex for F072 in your test environment?

Would you be willing to share your hex file for the same board and I will run the test myself?

 

Regards

Daniel

**Comment by majbthrd** [comment]
None of your attachments came through.  It may appear to you to be an email conversation, but all your messages (including your github management URLs) are posted publicly here (and for very good reason, Github strips out any attachments):

https://github.com/majbthrd/CDCHIDwidget/issues/1

I would NEVER program some random image into a microcontroller, much less then plug said device into a PC.  That the "meta-designs.com" URL that you have on your github page is indicated by Google to be a source of malware only strengthens the reason why this is a bad idea.

**Comment by danielsulik** [comment]
Please can you  send me  a link which lists my site as  source of malware?

I did not notice github stripped off the attachement, my bad.

 

I can still attach the hex to github. Are you willing to look at that? Just hex no other files if you are afraid.

 

Regards

Daniel

**Comment by danielsulik** [comment]
https://github.com/danielsulik/Private/blob/master/err.png

**Comment by danielsulik** [comment]
Hello again,

sorry to bother you again. I have a bit of time to look at the issue and want to ask you if you can share your CDCHIDwidget hex file for the F072 board. I was trying to build it under Crossworks 4.4.3 as you suggest however the built code does not work at all. Device does not appear on USB bus. If I build it under eclipse with gcc the HID interface works ok, however CDC i/f does not. 
I will try to break it with my test harness. I appreciate your help.

Regards
Daniel

**Comment by majbthrd** [comment]
I think you may be out of your depth.  However, as a final courtesy, I've: a) added another commit with the memcpy Vendor HID loopback as previously discussed, and b) provided the project with downloadable .hex and .srec images (see Releases tab; these are compiled by the very same Crossworks 4.4.3 and verified under both Linux and Window as functional).

**Comment by danielsulik** [comment]
Hi again
and thank you for your courtesy. 
I managed to break your code in few more ways including the problem I described earlier. As a courtesy to you I am sending you cut-down version of my test harness. Please get it from the link below
https://github.com/danielsulik/Private/releases/tag/1

Your CDC interface is badly broken. If you run CDC interface test (without HID running) as follows your CDC interface freezes in loopback mode.

tclsh cdctest.tcl -c /dev/ttyACM0 -l 1234 -n 10000 -rl
-l means max packet len is 1234 bytes, -n tries to run 10000 packets, -rl means generate random length
you can also break it with linearly incremented packet length (-il option)
tclsh cdctest.tcl -c /dev/ttyACM0 -l 1234 -n 10000 -il

Only hard reset makes your code usable again.
 
Your CDC i/f survives only if packet length is below 64 bytes. I guess you have  problem with ZLP.
tclsh cdctest.tcl -c /dev/ttyACM0 -l 63 -n 10000 

Your code also breaks when HID is running. Run CDC first with -l <= 63
tclsh cdctest.tcl -c /dev/ttyACM0 -l 63 -n 10000 
then run sudo ./loophid.sh, no data transfer is actually needed on HID, just opening and closing HID i/f.

I run these tests on ubuntu 16 and 18, RPI, Windows, all breaks.
Your original HID test is very poor and have not seen your cdc test code yet. I hope it does not have the same weakness.

If you need more info or help from me let me know.
If you think you know where the problem is please let me know. I am interested only in the data corruption issue when opening HID. My CDC i/f does not suffer the issues I discovered with yours.
I do not blame you in any way, just bit of modesty at your side might be helpful :-). No one is perfect, neither I am.
Thank you for your patience.
Best regards
Daniel

P.S: WRT to another layer for hidapi you mentioned in the previous responses. Originally I needed this for portable code to work on linux and windows, hence the extra layer to integrate it with  Tk. I believe that comment was out of your depth :-)
